export const metadata = {
  title: "Home",
  description: "Generated by Next.js",
};

import { Button } from "antd";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/navigation";

const MainPage = async () => {
  let ProductDetails = [];
  try {
    const response = await axios.get(
      "http://localhost:8000/products/allProducts"
    );

    ProductDetails = response.data.productDetails;
  } catch (e) {
    return <>something went wrong</>;
  }

  return (
    <>
      <div className="  w-[100vw] h-[100vh]  bg-gray-700 ">
        <div className="flex justify-center bg-[whitesmoke]  p-4 ">
          <p>Welcome to Bouddha Sports Shop </p>
        </div>

        <div className=" flex justify-center   ">
          <div className="gridContainer grid   w-[70%]   p-10 gap-3 ">
            {ProductDetails.map((element: any) => (
              <>
                <div className="product-container flex flex-col items-center  gap-5  border-2 border-gray-500 rounded-sm p-5 bg-[whitesmoke] h-[max-content]">
                  <div className="flex flex-col items-center flex-wrap gap-2">
                    <div
                      style={{
                        backgroundImage: `url(${element.ProductImage})`,
                      }}
                      className="productImage h-[100px] w-[100px]"
                    ></div>{" "}
                    <p>{element.ProductName}</p>
                  </div>
                  <div>
                    {" "}
                    <Link
                      href={`http://localhost:3000/productDetails/${element._id}`}
                    >
                      <Button type="primary">Details</Button>
                    </Link>
                  </div>
                </div>
              </>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};
export default MainPage;
